defmodule Campfire.Repo.Migrations.MigrateResources1 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up() do
    create table(:users, primary_key: false) do
      add(:id, :binary_id, null: true, default: nil, primary_key: true)
      add(:last_name, :text, null: true, default: nil, primary_key: false)
      add(:first_name, :text, null: true, default: nil, primary_key: false)
      add(:email, :text, null: false, default: nil, primary_key: false)
      add(:admin, :boolean, null: false, default: false, primary_key: false)
    end

    create table(:messages, primary_key: false) do
      add(:id, :binary_id, null: true, default: nil, primary_key: true)
      add(:subject, :text, null: true, default: nil, primary_key: false)
      add(:status, :text, null: false, default: "new", primary_key: false)
      add(:response, :text, null: true, default: nil, primary_key: false)
      add(:description, :text, null: true, default: nil, primary_key: false)

      add(:recipient_id, references("users", type: :binary_id, column: :id),
        default: nil,
        primary_key: false
      )

      add(:sender_id, references("users", type: :binary_id, column: :id),
        default: nil,
        primary_key: false
      )
    end
  end

  def down() do
    drop(table("messages"))

    drop(table("users"))
  end
end
